# Generated by Django 2.2.8 on 2020-04-20 17:58

import app.parameter.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genetic_element', '0001_initial'),
        ('specie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Used for interface display', max_length=255)),
                ('alias', models.CharField(help_text='For internal usage. Must match checker list', max_length=255, unique=True)),
                ('matrix_file', models.FileField(blank=True, help_text='Matrix file', null=True, upload_to=app.parameter.models.species_dir)),
                ('genome_min', models.FloatField(default=0)),
                ('genome_max', models.FloatField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Determine if it can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('genetic_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetic_element.GeneticElement')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specie.Specie')),
            ],
            options={
                'unique_together': {('alias', 'specie', 'genetic_element')},
            },
        ),
    ]
